# Generated by Django 5.2.7 on 2025-10-27 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01, message='El peso debe estar entre 10 gramos y 200 kilos'), django.core.validators.MaxValueValidator(200, message='El peso debe estar entre 10 gramos y 200 kilos')])),
                ('vacunado', models.BooleanField(default=False)),
                ('ultima_vacuna', models.DateField(blank=True, null=True)),
                ('email_duenyo', models.EmailField(blank=True, max_length=254, null=True)),
                ('domicilio_duenyo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
